CREATE DATABASE `webgoods`;

USE `webgoods`;

/*用户表：user*/
DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) DEFAULT NULL COMMENT '用户名称（必须是电话号码）',
	`pwd`  VARCHAR(20) DEFAULT NULL COMMENT '必须6位以上',
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11)  DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL COMMENT '用户',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',	
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*门店表：store*/
DROP TABLE IF EXISTS `store`;

CREATE TABLE `store` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) DEFAULT NULL COMMENT '门店名称',
	`Province` VARCHAR(50) DEFAULT NULL COMMENT '省',
	`City` VARCHAR(50) DEFAULT NULL COMMENT '市',
	`district` VARCHAR(50) DEFAULT NULL COMMENT '区',
	`address` VARCHAR(50) DEFAULT NULL COMMENT '详细地址',
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`stid` INT(11) DEFAULT NULL COMMENT '门店类型',
	`Parented` VARCHAR(20) DEFAULT NULL COMMENT '自我关联',
	`status` INT(20) DEFAULT '0' COMMENT '是否删除0，1删除,2冻结，3过期',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*门店类型storeType*/
DROP TABLE IF EXISTS `storeType`;

CREATE TABLE `storeType` (
	`Id`  INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) DEFAULT NULL COMMENT '门店类型名称',
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`Level` INT(11) DEFAULT '1' COMMENT'级别，从1开始，数字越大级别越小',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT'同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*门店与用户：storeuser*/
DROP TABLE IF EXISTS `storeuser`;

CREATE TABLE `storeuser` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`userid` INT(11) DEFAULT NULL,
	`sid` INT(11) DEFAULT NULL COMMENT'门店编号',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT'同步',
	`uid` VARCHAR(50) DEFAULT NULL COMMENT'操作人的Id',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*模块表：module*/
DROP TABLE IF EXISTS `module`;

CREATE TABLE `module` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) DEFAULT NULL COMMENT '中文名称',
	`enname` VARCHAR(50) DEFAULT NULL COMMENT '英文名称',
	`catalog` INT(11) DEFAULT NULL COMMENT '是否为目录0，目录，1，功能',
	`url` VARCHAR(50) DEFAULT NULL COMMENT '模块地址',
	`funtype` INT(11) DEFAULT NULL COMMENT '功能类型，0跳转页面，1，ajax',
	`type` INT(11) DEFAULT NULL COMMENT '模块类型0为pc功能，1为app功能',
	`fun` VARCHAR(50) DEFAULT NULL COMMENT '如果是ajax则需要触发js函数',
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`Parentid` INT(11) DEFAULT NULL COMMENT '自我关联',
	`Status` INT(11) DEFAULT '0' COMMENT '状态0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*角色表：role*/
DROP TABLE IF EXISTS `role`;

CREATE TABLE `role` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) DEFAULT NULL COMMENT '角色名称',
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`Status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*角色用户：roleuser*/
DROP TABLE IF EXISTS `roleuser`;

CREATE TABLE `roleuser` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`uid` INT(11) DEFAULT NULL COMMENT '用户编号',
	`rid` INT(11) DEFAULT '1' COMMENT '角色编号',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*角色模块：rolemodule*/

DROP TABLE IF EXISTS `rolemodule`;

CREATE TABLE `rolemodule` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`mid` INT(11) DEFAULT NULL COMMENT '模块编号',
	`rid` INT(11) DEFAULT '1' COMMENT '角色编号',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品表：goods*/
DROP TABLE IF EXISTS `goods`;

CREATE TABLE `goods` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(40) DEFAULT NULL COMMENT'商品名称',
	`Tid` INT(11) DEFAULT NULL COMMENT '商品类型编号goodstype表',
	`Bid` INT(11) DEFAULT NULL COMMENT '商品单位表：bit表',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`Code` VARCHAR(20) DEFAULT NULL COMMENT'商品编码',
	`Codeprev`  VARCHAR(20) DEFAULT NULL COMMENT'商品编码前缀',
	`Detail` TEXT DEFAULT NULL COMMENT'商品详细',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号：store',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品实例：goodsinstance*/
DROP TABLE IF EXISTS `goodsinstance`;

CREATE TABLE `goodsinstance` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`ids` VARCHAR(20) DEFAULT NULL COMMENT'实例编号例如：1，2，3如果为默认实例则为-1',
	`Gid` INT(11) DEFAULT NULL COMMENT '商品编号，goods表',
	`Ecode` VARCHAR(50) DEFAULT NULL COMMENT'二维码地址',
	`Qcode` VARCHAR(50) DEFAULT NULL COMMENT'条码地址',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`DefaultState` INT(11) DEFAULT '0' COMMENT '0 非默认1默认一口价',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品价格表：goodsinstanceprice*/
DROP TABLE IF EXISTS `goodsinstanceprice`;

CREATE TABLE `goodsinstanceprice` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Ptype` VARCHAR(50) DEFAULT NULL COMMENT'商品价格折扣名称',
	`price` INT(255) DEFAULT NULL COMMENT '价格',
	`goodsinstanceid` VARCHAR(20) DEFAULT NULL COMMENT'商品实例',
	`Sid` INT(255) DEFAULT NULL COMMENT '门店编号：store',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品价格折扣表：pricetype*/
DROP TABLE IF EXISTS `pricetype`;

CREATE TABLE `pricetype` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`userStyleId` INT(11) DEFAULT NULL COMMENT'客户类别关联userStyle',
	`Name` VARCHAR(20) DEFAULT NULL COMMENT'价格名称',
	`Agio` INT(50) DEFAULT NULL COMMENT '折扣',
	`DefaultPrice` INT(50) DEFAULT NULL COMMENT '是否为默认1默认，一般零售为默认',
	`Sid` INT(50) DEFAULT NULL COMMENT '门店编号：store',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*例如一个商品实例有这些价格：exampleprice*/
DROP TABLE IF EXISTS `exampleprice`;

CREATE TABLE `exampleprice` (
	`pprice` INT(11) DEFAULT NULL COMMENT'批发价格',
	`dprice` VARCHAR(50) DEFAULT NULL COMMENT'打包价格',
	`sprice` VARCHAR(250) DEFAULT NULL COMMENT'原价格',
	`cprice` VARCHAR(250) DEFAULT NULL COMMENT'出售价格',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义'
)DEFAULT CHARSET=utf8;

/*商品规格表：standard*/
DROP TABLE IF EXISTS `standard`;

CREATE TABLE `standard` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'规格名称',
	`Tid` INT(11) DEFAULT NULL COMMENT'商品类型编号：Goodstype',
	`Gid` INT(11) DEFAULT NULL COMMENT'商品编号goods表，如果有商品编号表示为自定义的规格，没有',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL COMMENT '操作员编号',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*规格实例表：Standardinstance*/
DROP TABLE IF EXISTS `Standardinstance`;

CREATE TABLE `Standardinstance` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'规格实例名称',
	`sid` INT(11) DEFAULT NULL COMMENT'规格编号：standard',
	`Gid` INT(11) DEFAULT NULL COMMENT'商品编号goods表，如果有商品编号表示为自定义的规格实例，没有则是为默认规格实例',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL COMMENT '操作员编号',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品类型表：goodstype*/
DROP TABLE IF EXISTS `goodstype`;

CREATE TABLE `goodstype` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'类型名称',
	`Parentid` INT(11) DEFAULT NULL COMMENT'自我关联',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*图片表：img*/
DROP TABLE IF EXISTS `img`;

CREATE TABLE `img` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'新名称',
	`Oldname` VARCHAR(50) DEFAULT NULL COMMENT'上传前的名称',
	`url` VARCHAR(50) DEFAULT NULL COMMENT'图片地址',
	`imgtype` INT(11) DEFAULT '1' COMMENT '图片类型，1为',
	`Gid` INT(11) DEFAULT NULL COMMENT '商品编号',
	`Goodsinstanceid` INT(11) DEFAULT NULL COMMENT '商品实例编号如果图片类型为2的时候才会有，但是一样的要存储gid',
	`time`	DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*商品单位：bit*/
DROP TABLE IF EXISTS `bit`;

CREATE TABLE `bit` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'单位名称',
	`time`	DATETIME DEFAULT NULL COMMENT '创建时间',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号：store',
	`status`INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*客户表：customer*/
DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'客户名称',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号：Store',
	`Lid` INT(11) DEFAULT NULL COMMENT '客户级别Customerlevel',
	`Phone` VARCHAR(50) DEFAULT NULL COMMENT'联系电话',
	`Province` VARCHAR(50) DEFAULT NULL COMMENT'省',
	`City` VARCHAR(50) DEFAULT NULL COMMENT'市',
	`District` VARCHAR(50) DEFAULT NULL COMMENT'区',
	`Addres` VARCHAR(50) DEFAULT NULL COMMENT'详细地址',
	`Balance` DOUBLE DEFAULT NULL COMMENT'余额',
	`freezemoney` DOUBLE DEFAULT NULL COMMENT'冻结金额',
	`Remark` VARCHAR(50) DEFAULT NULL COMMENT'备注',
	`Code` VARCHAR(50) DEFAULT NULL COMMENT'会员号，以门店前缀定义开始',
	`Core` DOUBLE DEFAULT NULL COMMENT'冻结金额',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*客户级别：customerlevel*/
DROP TABLE IF EXISTS `customerlevel`;

CREATE TABLE `customerlevel` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) DEFAULT NULL COMMENT'单位名称',
	`Agio` INT(11) DEFAULT NULL COMMENT '折扣',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号Store',
	`time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*客户充值表：customerrecharge*/
DROP TABLE IF EXISTS `customerrecharge`;

CREATE TABLE `customerrecharge` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Time` DATETIME DEFAULT NULL COMMENT '创建时间',
	`money` DOUBLE DEFAULT NULL COMMENT'充值金额，可以为负数，负数则提取',
	`cid` INT(11) DEFAULT NULL COMMENT '客户编号customer',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*库存表：stock  在添加商品的时候默认需要添加库存表中的内容*/
DROP TABLE IF EXISTS `stock`;

CREATE TABLE `stock` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Code` VARCHAR(20) DEFAULT NULL COMMENT'批次号:年月日+每天的自增值，自增值为四位，不够四位前面补0',
	`Allprice` DOUBLE DEFAULT NULL COMMENT'这批次总共进货价格',
	`Allcount` INT(11) DEFAULT NULL COMMENT '总进货数量',
	`Time` DATETIME DEFAULT NULL COMMENT '时间',
	`Sid`  INT(11) DEFAULT NULL COMMENT '门店编号：store',
	`Supid` INT(11) DEFAULT NULL COMMENT '供应商编号supplier，如果为空则表示没有供应商属于散货',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*库存详细表：stockdetail*/
DROP TABLE IF EXISTS `stockdetail`;

CREATE TABLE `stockdetail` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Goodsinstanceid` INT(11) DEFAULT NULL COMMENT '商品实例编号Goodsinstance',
	`Sid` INT(11) DEFAULT NULL COMMENT '库存主表编号stock',
	`count` INT(11) DEFAULT NULL COMMENT '进货数量',
	`scount` INT(11) DEFAULT NULL COMMENT'出售数量 ，剩余数量等于count-scount',
	`Sum` DOUBLE DEFAULT NULL COMMENT'进货总价格',
	`Price` DOUBLE DEFAULT NULL COMMENT'进货单价格',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*库存门店分配记录表：stocksstoreinfo  分配库存的是需要修改原来的库存数量，添加其它门店的库存*/

DROP TABLE IF EXISTS `stocksstoreinfo`;

CREATE TABLE `stocksstoreinfo` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Sid` INT(11) DEFAULT NULL COMMENT '新门店编号：store',
	`oldsid` INT(11) DEFAULT NULL COMMENT '来源的哪个门店库存的门店编号：store',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status`  INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*库存门店分配记录详细表：stocksstoreinfodetail*/
DROP TABLE IF EXISTS `stocksstoreinfodetail`;

CREATE TABLE `stocksstoreinfodetail` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Sid` INT(11) DEFAULT NULL COMMENT '主表编号',
	`Goodsinstanceid` INT(11) DEFAULT NULL COMMENT '商品实例编号',
	`Count` INT(11) DEFAULT NULL COMMENT '分配的数量',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status`  INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*支付类型：paytype*/
DROP TABLE IF EXISTS `paytype`;

CREATE TABLE `paytype` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(20) DEFAULT NULL COMMENT'支付类型名称',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status`  INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*销售表：Sales*/
DROP TABLE IF EXISTS `Sales`;

CREATE TABLE `Sales` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`money` DOUBLE DEFAULT NULL COMMENT'出售总价(没打折的价格，也就是商品原价的总和)',
	`count` INT(11) DEFAULT NULL COMMENT '出售总数量',
	`Takeinmoney` VARCHAR(255) DEFAULT NULL COMMENT'实际支付金额（零售价格综合，如果是客户，按照客户等级进行再次打折后的价格）',
	`cid` INT(11) DEFAULT NULL COMMENT '出售客户：如果没选择客户则为-1(显示散客)',
	`Pid`  INT(11) DEFAULT NULL COMMENT '支付类型paytype',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号：store',
	`time`  DATETIME DEFAULT NULL COMMENT '时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`deposi` DOUBLE DEFAULT NULL COMMENT'定金',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*销售详细表：Salesdetails*/
DROP TABLE IF EXISTS `Salesdetails`;

CREATE TABLE `Salesdetails` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Salesid` INT(11) DEFAULT NULL COMMENT '出售主表编号',
	`money` DOUBLE DEFAULT NULL COMMENT'出售的商品实例的总价(没打折的价格，也就是商品原价的总和)',
	`count` INT(11) DEFAULT NULL COMMENT '出售商品实例的总数量',
	`Takeinmoney` DOUBLE DEFAULT NULL COMMENT'实际支付金额（零售价格综合，如果是客户，按照客户等级进行再次打折后的价格）',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*销售库存记录表：salesstockinfo*/
DROP TABLE IF EXISTS `salesstockinfo`;

CREATE TABLE `salesstockinfo` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`salesid` INT(11) DEFAULT NULL COMMENT '出售详表编号Salesdetail',
	`stockdetailid`  INT(11) DEFAULT NULL COMMENT '库存详细表编号stockdetail',
	`count` INT(11) DEFAULT NULL COMMENT '出售数量',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;
/*供应商编号：supplier*/
DROP TABLE IF EXISTS `supplier`;

CREATE TABLE `supplier` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(20) DEFAULT NULL COMMENT'供应商名称',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号：Store',
	`Lid` INT(11) DEFAULT NULL COMMENT '供应商级别supplierlevel',
	`Phone` VARCHAR(50) DEFAULT NULL COMMENT'联系电话',
	`Province` VARCHAR(50) DEFAULT NULL COMMENT'省',
	`City` VARCHAR(50) DEFAULT NULL COMMENT'市',
	`District` VARCHAR(50) DEFAULT NULL COMMENT'区',
	`Addres` VARCHAR(50) DEFAULT NULL COMMENT'详细地址',
	`Balance` DOUBLE DEFAULT NULL COMMENT'余额',
	`freezemoney` DOUBLE DEFAULT NULL COMMENT'冻结金额',
	`Remark` VARCHAR(255) DEFAULT NULL COMMENT'备注',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*供应商级别：supplierlevel*/
DROP TABLE IF EXISTS `supplierlevel`;

CREATE TABLE `supplierlevel` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(20) DEFAULT NULL COMMENT'级别名称',
	`Agio` INT(11) DEFAULT NULL COMMENT '折扣',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号Store',
	`time` DATETIME DEFAULT NULL COMMENT '时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*付款表：remittance*/
DROP TABLE IF EXISTS `remittance`;

CREATE TABLE `remittance` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`money` DOUBLE DEFAULT NULL COMMENT'汇款金额，可以为负数，负数则供应商返的金额',
	`Sid` VARCHAR(20) DEFAULT NULL COMMENT'供应商编号supplier',
	`Time` DATETIME DEFAULT NULL COMMENT '时间',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*销售订单salesindent*/
DROP TABLE IF EXISTS `salesindent`;

CREATE TABLE `salesindent` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`money` DOUBLE DEFAULT NULL COMMENT'出售总价',
	`count` INT(11) DEFAULT '0' COMMENT '出售总数量',
	`cid` VARCHAR(50) DEFAULT NULL COMMENT'客户',
	`SalesIndentNub` VARCHAR(50) DEFAULT NULL COMMENT'销售订单',
	`Sid` INT(11) DEFAULT NULL COMMENT '门面编号',
	`pid` DOUBLE DEFAULT NULL COMMENT'支付类型',
	`remark` VARCHAR(250) DEFAULT NULL COMMENT'备注',
	`time` DATETIME DEFAULT NULL COMMENT '订单日期',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`deposi` DOUBLE DEFAULT NULL COMMENT'定金',
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

/*(新增)客户类型表userStyle*/
DROP TABLE IF EXISTS `userStyle`;

CREATE TABLE `userStyle` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(20) DEFAULT NULL COMMENT '名称',
	`Sid` INT(11) DEFAULT NULL COMMENT '门店编号Store',
	`time` DATETIME DEFAULT NULL COMMENT '订单日期',
	`status` INT(11) DEFAULT '0' COMMENT '是否删除0，1删除',
	`async` INT(11) DEFAULT NULL COMMENT '同步',
	`uid` VARCHAR(50) DEFAULT NULL,
	`user1` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user2` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user3` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user4` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	`user5` VARCHAR(50) DEFAULT NULL COMMENT '自定义',
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;